/*
Document created by Hussein Hussein
Student ID: 103615588
*/ 

USE BUILDQUERYCHALLENGE

/* 

SUBJECT(SUBJCODE, DESCRIPTION)
PRIMARY KEY(SUBJCODE)

TEACHER(STAFFID, SURNAME, GIVENNAME)
PRIMARY KEY(STAFFID)

STUDENT(STUDENTID, SURNAME, GIVENNAME, GENDER)
PRIMARY KEY(STUDENTID)

SUBJECTOFFERING(YEAR, STAFFID, SUBJCODE, SEMESTER, FEE)
PRIMARY KEY(YEAR, SEMESTER, STAFFID, SUBJCODE)
FOREIGN KEY(SUBJCODE) REFERENCES SUBJECT
FOREIGN KEY(STAFFID) REFERENCES TEACHER

ENROLMENT(YEAR, SEMESTER, STAFFID, SUBJCODE, STUDENTID, DATEENROLLED, GRADE)
PRIMARY KEY(YEAR, SEMESTER, STAFFID, SUBJCODE, STUDENTID)
FOREIGN KEY(YEAR, SEMESTER, STAFFID, SUBJCODE) REFERENCES SUBJECTOFFERING
FOREIGN KEY(STUDENTID) REFERENCES STUDENT

*/
DROP TABLE IF EXISTS ENROLMENT, SUBJECTOFFERING, STUDENT, TEACHER, SUBJECT;


CREATE TABLE SUBJECT(
    SUBJCODE nvarchar(100), 
    DESCRIPTION nvarchar(500),
    PRIMARY KEY(SUBJCODE)
);
    
CREATE TABLE TEACHER(
    STAFFID INT,  
    SURNAME nvarchar(100) NOT NULL,
    GIVENNAME nvarchar(100) NOT NULL
    PRIMARY KEY(STAFFID),
    CONSTRAINT chk_staffid_length CHECK(LEN(STAFFID)=8),
);

CREATE TABLE STUDENT(
    STUDENTID nvarchar(10),
    SURNAME nvarchar(100) NOT NULL, 
    GIVENNAME nvarchar(100) NOT NULL, 
    GENDER nvarchar(1),
    PRIMARY KEY(STUDENTID),
    CONSTRAINT chk_thestudent_gender CHECK (GENDER IN ('M', 'F', 'I')),
);

CREATE TABLE SUBJECTOFFERING(
    SUBJCODE nvarchar(100),
    YEAR INT, 
    STAFFID INT, 
    SEMESTER INT , 
    FEE MONEY NOT NULL,
    PRIMARY KEY(YEAR, SEMESTER, STAFFID, SUBJCODE),
    FOREIGN KEY(SUBJCODE) REFERENCES SUBJECT,
    FOREIGN KEY(STAFFID) REFERENCES TEACHER,
    CONSTRAINT chk_year_length CHECK(LEN(YEAR)=4),
    CONSTRAINT chk_sem_digits CHECK (SEMESTER IN ('1', '2')),
    CONSTRAINT chk_fee CHECK (FEE > 0)
);

CREATE TABLE ENROLMENT(
    YEAR INT, 
    SEMESTER INT, 
    STAFFID INT, 
    SUBJCODE NVARCHAR(100), 
    STUDENTID NVARCHAR(10), 
    DATEENROLLED DATE, 
    GRADE NVARCHAR(2) DEFAULT NULL,
    PRIMARY KEY(YEAR, SEMESTER, STAFFID, SUBJCODE, STUDENTID),
    FOREIGN KEY(YEAR, SEMESTER, STAFFID, SUBJCODE) REFERENCES SUBJECTOFFERING,
    FOREIGN KEY(STUDENTID) REFERENCES STUDENT,
    CONSTRAINT chk_enrolyear_length CHECK(LEN(YEAR)=4),
    CONSTRAINT chk_erolsem_digits CHECK (SEMESTER IN ('1', '2')),
    CONSTRAINT chk_grade CHECK (GRADE IN ('N', 'P', 'C', 'D', 'HD')),
);

SELECT NAME 
FROM sys.objects 
WHERE TYPE = 'U'





